### Dockerfile.base ###
FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive

# Create non-root user
RUN useradd -m -s /bin/bash texuser

# Install base TeX packages
RUN apt-get update && \
    apt-get install -y \
    texlive-base \
    latexmk && \
    rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /workdir

RUN chown texuser:texuser /workdir

# Switch to non-root user
USER texuser
