### Dockerfile.recommended ###
FROM texlive-base

# Switch to root user
USER root

# Install recommended TeX packages
RUN apt-get update && \
    apt-get install -y \
    texlive-latex-recommended \
    texlive-fonts-recommended && \
    rm -rf /var/lib/apt/lists/*

# Switch to non-root user
USER texuser
