name: Build and Push Docker Images

on:
  push:
    branches: [ master ]
    paths:
      - 'Dockerfile.*'
      - '.github/workflows/docker-build.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'Dockerfile.*'
  workflow_dispatch:

env:
  GHCR_REGISTRY: ghcr.io
  DOCKERHUB_REGISTRY: docker.io
  GHCR_IMAGE: ${{ github.repository }}
  DOCKERHUB_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/texlive

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push base
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.base
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.GHCR_REGISTRY }}/${{ env.GHCR_IMAGE }}-base:latest
            ${{ env.DOCKERHUB_REGISTRY }}/${{ env.DOCKERHUB_IMAGE }}-base:latest

      - name: Build and push recommended
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.recommended
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.GHCR_REGISTRY }}/${{ env.GHCR_IMAGE }}-recommended:latest
            ${{ env.DOCKERHUB_REGISTRY }}/${{ env.DOCKERHUB_IMAGE }}-recommended:latest
        
      - name: Build and push extra
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.extra
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.GHCR_REGISTRY }}/${{ env.GHCR_IMAGE }}-extra:latest
            ${{ env.DOCKERHUB_REGISTRY }}/${{ env.DOCKERHUB_IMAGE }}-extra:latest
        

      - name: Build and push full
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.full
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.GHCR_REGISTRY }}/${{ env.GHCR_IMAGE }}-full:latest
            ${{ env.DOCKERHUB_REGISTRY }}/${{ env.DOCKERHUB_IMAGE }}-full:latest
